# Generated by Django 5.1.6 on 2025-03-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="location",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="skills",
        ),
        migrations.AddField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Nascimento"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="cep",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="CEP"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="children_age_groups",
            field=models.JSONField(
                default=list,
                verbose_name="Escolha a faixa etária dos seus filhos (pode marcar mais de uma faixa etária)",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Cidade"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="house_number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Número da Casa"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="interests",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Interesses e Hobbies (ex: novelas, filmes, culinária, yoga, leitura, musculação, esportes, viagens, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="neighborhood",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Bairro"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="number_of_children",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Quantos filhos você tem? (Use somente números)",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="services_needed",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Serviços Procurados (O que você busca nas conexões desta comunidade? ex: troca de experiências, apoio para o cuidado dos filhos, receber caronas, alguém que possa dar aulas de reforço para seus filhos, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="services_offered",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Serviços Oferecidos (O que você gostaria de compartilhar nesta rede? ex: dar aulas de yoga, cuidar de crianças, oferecer caronas, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="state",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Estado"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="street",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Rua"
            ),
        ),
    ]
